### ISSUE TITLE
El id del producto no es autogenerado

### ISSUE THREAD

**Issue by Lainezz** [aanillo/ProyectoStockControl#1]
https://github.com/aanillo/ProyectoStockControl/blame/e0a95baf221d84c5445fff11b4ab064e5b2f7481/src/main/java/com/es/stockcontrol/model/Producto.java#L11

El id del producto no es autogenerado. Si miráis la documentación del Service, veréis que ese id lo tenéis que poner vosotros.
Quita la anotación @GeneratedValue

**Comment by aanillo** [comment]
He quitado la anotación @GeneratedValue para así tener ya un id que se pueda aplicar manualmente.
