### ISSUE TITLE
Ponle el fetch = FetchType.Lazy

### ISSUE THREAD

**Issue by Lainezz** [aanillo/ProyectoStockControl#2]
https://github.com/aanillo/ProyectoStockControl/blame/e0a95baf221d84c5445fff11b4ab064e5b2f7481/src/main/java/com/es/stockcontrol/model/Proveedor.java#L16

Ponle la propiedad fetch = FetchType.Lazy

**Comment by Django777DGB** [comment]
Ya he añadido la propiedad 
![correccion1](https://github.com/user-attachments/assets/5a521971-6e97-4bc5-8165-a220b7a7551c)
